services:
  db:
    container_name: ${NAME}_db
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootwordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    build:
      context: ./
    container_name: "${NAME}_wp"
    volumes:
      - wordpress:/var/www/html
      - ./frontend/themes/mytheme:/var/www/html/wp-content/themes/mytheme:rw
      #- ./frontend/plugins/myplugin:/var/www/html/wp-content/plugins/myplugin:rw
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    command: >

volumes:
  wordpress:
  db:

#  wp-data:
